version: '3.4'
services:
 eshopwebmvc:
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5106:80"
  #  volumes:
  #    - ~/AppData/Roaming/Asp.Net/Https:/root/.aspnet/https:ro
  #    - ~/AppData/Roaming/Microsoft/usersecrets:/root/.microsoft/usersecrets:ro
 eshoppublicapi:
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5200:80"
  #  volumes:
  #    - ~/AppData/Roaming/Asp.Net/Https:/root/.aspnet/https:ro
  #    - ~/AppData/Roaming/Microsoft/usersecrets:/root/.microsoft/usersecrets:ro